### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by eloo** [corona-hub-germany/corona-lgl-bayern-scraper#1]
Hi,

it would be great if a license could be added to the project so its clear how this project can be used.

I would recommend the MIT license as this license is really common in the open source community.

More information about different licenses can be found here https://choosealicense.com/

Thanks

**Comment by mojoaxel** [comment]
@eloo This software is licensed under [AGPL-3.0-or-later](https://github.com/corona-hub-germany/corona-lgl-bayern-scraper/blob/master/package.json#L19).

**Comment by eloo** [comment]
@mojoaxel 
Sounds good. 
Would you mind to add this to the code as well? Maybe as a LICENSE file or as a note in the readme?

Thanks

**Comment by mojoaxel** [comment]
I'm open for pull-requests 😉
